# Generated by Django 6.0.2 on 2026-02-10 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(help_text="e.g., 'Once daily', 'Twice daily'", max_length=100)),
                ('scheduled_times', models.JSONField(help_text="List of scheduled times in HH:MM format, e.g., ['09:00', '21:00']")),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('reminder_advance_minutes', models.IntegerField(default=15, help_text='How many minutes before scheduled time to send reminder')),
                ('verification_window_minutes', models.IntegerField(default=60, help_text='How many minutes after scheduled time before escalation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_times'],
            },
        ),
        migrations.CreateModel(
            name='MedicationIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField()),
                ('verified_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('missed', 'Missed'), ('partially_verified', 'Partially Verified')], default='pending', max_length=20)),
                ('medication_image', models.TextField(blank=True, help_text='Base64 encoded image of medication verification')),
                ('medication_detected', models.BooleanField(default=False)),
                ('face_detected', models.BooleanField(default=False)),
                ('position_verified', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('ai_verification_result', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_sent', models.BooleanField(default=False)),
                ('escalation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='orbitb.medicationschedule')),
            ],
            options={
                'ordering': ['-scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('medication_reminder', 'Medication Reminder'), ('missed_dose', 'Missed Dose Alert'), ('symptom_alert', 'Symptom Alert'), ('mental_health_alert', 'Mental Health Alert'), ('checkin_reminder', 'Check-in Reminder')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('medication_intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orbitb.medicationintake')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_type', models.CharField(default='encouragement', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('healthcare_worker', 'Healthcare Worker')], default='patient', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('patient_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('treatment_start_date', models.DateField(blank=True, null=True)),
                ('treatment_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregivers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'caregiver'}, related_name='patients_cared_for', to='orbitb.userprofile')),
                ('healthcare_workers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'healthcare_worker'}, related_name='patients_managed', to='orbitb.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentalHealthCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('mood_score', models.IntegerField(blank=True, help_text='1=Very Poor, 10=Excellent', null=True)),
                ('stress_level', models.IntegerField(blank=True, help_text='1=No Stress, 10=Extreme Stress', null=True)),
                ('motivation_level', models.IntegerField(blank=True, help_text='1=No Motivation, 10=Very Motivated', null=True)),
                ('sleep_quality', models.IntegerField(blank=True, help_text='1=Very Poor, 10=Excellent', null=True)),
                ('feeling_supported', models.BooleanField(blank=True, null=True)),
                ('treatment_burden', models.IntegerField(blank=True, help_text='1=Not Burdensome, 10=Very Burdensome', null=True)),
                ('notes', models.TextField(blank=True)),
                ('disengagement_risk_score', models.FloatField(blank=True, null=True)),
                ('requires_support', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mental_health_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in_date'],
                'unique_together': {('patient', 'check_in_date')},
            },
        ),
        migrations.CreateModel(
            name='SymptomCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('cough', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=10)),
                ('fever', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=10)),
                ('night_sweats', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=10)),
                ('weight_loss', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=10)),
                ('fatigue', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=10)),
                ('chest_pain', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=10)),
                ('nausea', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=10)),
                ('appetite_loss', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=10)),
                ('vision_problems', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=10)),
                ('joint_pain', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=10)),
                ('additional_notes', models.TextField(blank=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('requires_attention', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in_date'],
                'unique_together': {('patient', 'check_in_date')},
            },
        ),
    ]
